using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace TMS.Web.Services
{
    /// <summary>
    /// Converts PPT/PPTX slides to PNG images using LibreOffice headless.
    /// Completely independent of DocumentViewerController / PDF conversion.
    /// Output: wwwroot/ppt-preview/{pptId}/slide_{n}.png
    /// </summary>
    public interface IInteractivePPTService
    {
        /// <summary>
        /// Returns the output directory for slide images, running conversion if needed.
        /// Returns (slideCount, outputDir) on success, (0, null) on failure.
        /// </summary>
        Task<(int slideCount, string? outputDir, string? error)> EnsureSlidesConvertedAsync(
            int pptId, string physicalPptPath, CancellationToken ct = default);

        /// <summary>Returns number of PNG slides already in the output dir, or 0.</summary>
        int GetExistingSlideCount(int pptId, string webRootPath);

        string GetSlideOutputDir(int pptId, string webRootPath);
    }

    public class InteractivePPTService : IInteractivePPTService
    {
        private readonly string _libreOfficePath;
        private readonly string _webRootPath;
        private readonly ILogger<InteractivePPTService> _logger;

        // Static fallback paths (Windows + Linux)
        private static readonly string[] FallbackPaths = new[]
        {
            @"C:\Program Files\LibreOffice\program\soffice.exe",
            @"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
            "/usr/bin/soffice",
            "/usr/lib/libreoffice/program/soffice",
            "/usr/local/bin/soffice"
        };

        public InteractivePPTService(
            IConfiguration config,
            IWebHostEnvironmentAccessor envAccessor,
            ILogger<InteractivePPTService> logger)
        {
            _webRootPath = envAccessor.WebRootPath;
            _logger = logger;

            // 1. Try appsettings key "LibreOfficePath"
            var configPath = config["LibreOfficePath"];
            if (!string.IsNullOrEmpty(configPath) && File.Exists(configPath))
            {
                _libreOfficePath = configPath;
            }
            else
            {
                // 2. Auto-detect
                _libreOfficePath = FallbackPaths.FirstOrDefault(File.Exists) ?? FallbackPaths[0];
            }
        }

        public string GetSlideOutputDir(int pptId, string webRootPath) =>
            Path.Combine(webRootPath, "ppt-preview", pptId.ToString());

        public int GetExistingSlideCount(int pptId, string webRootPath)
        {
            var dir = GetSlideOutputDir(pptId, webRootPath);
            if (!Directory.Exists(dir)) return 0;
            return Directory.GetFiles(dir, "slide_*.png").Length;
        }

        public async Task<(int slideCount, string? outputDir, string? error)> EnsureSlidesConvertedAsync(
            int pptId, string physicalPptPath, CancellationToken ct = default)
        {
            var outDir = GetSlideOutputDir(pptId, _webRootPath);
            var markerPath = Path.Combine(outDir, ".converted_by_pymupdf");

            // ── Check cache & Verify PyMuPDF marker ──────────────────────
            if (Directory.Exists(outDir))
            {
                var cached = Directory.GetFiles(outDir, "slide_*.png");
                
                // If cached slides exist AND they were generated by our new engine, use them!
                if (cached.Length > 0 && File.Exists(markerPath))
                {
                    _logger.LogInformation("PPT {Id}: using {N} validated PyMuPDF cached slides", pptId, cached.Length);
                    return (cached.Length, outDir, null);
                }
                
                // Legacy invalidation: if it has 1 slide but NO PyMuPDF marker, it is a broken LibreOffice render!
                // Purge it completely so we can recreate it properly.
                if (cached.Length > 0 && !File.Exists(markerPath))
                {
                    _logger.LogWarning("PPT {Id}: Invalidating legacy single-slide LibreOffice cache. Purging and rebuilding...", pptId);
                    try
                    {
                        foreach (var file in cached) { File.Delete(file); }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "PPT {Id}: Failed to purge legacy cache files. Proceeding anyway.", pptId);
                    }
                }
            }

            if (!File.Exists(physicalPptPath))
                return (0, null, $"PPT file not found: {physicalPptPath}");

            if (!File.Exists(_libreOfficePath))
                return (0, null,
                    $"LibreOffice not found at '{_libreOfficePath}'. Install LibreOffice and set 'LibreOfficePath' in appsettings.json.");

            Directory.CreateDirectory(outDir);

            // ── Step 1: PPT → PDF (using LibreOffice) ──────────────────
            var pdfPath = await ConvertToPdfAsync(physicalPptPath, outDir, ct);
            if (pdfPath == null)
                return (0, null, "LibreOffice PPT→PDF conversion failed.");

            // ── Step 2: PDF → PNG slides (using PyMuPDF Python script) ──
            var slideCount = await ConvertPdfToSlidesAsync(pdfPath, outDir, ct);

            // Clean up intermediate PDF
            try { File.Delete(pdfPath); } catch { /* ignore */ }

            if (slideCount == 0)
                return (0, null, "No slide images were generated from the PDF.");

            // ── Step 3: Add conversion stamp file ──────────────────────
            try
            {
                await File.WriteAllTextAsync(markerPath, DateTime.UtcNow.ToString("O"), ct);
            }
            catch { /* ignore error writing tracker */ }

            _logger.LogInformation("PPT {Id}: {N} slides generated successfully via PyMuPDF in {Dir}", pptId, slideCount, outDir);
            return (slideCount, outDir, null);
        }

        // ────────────────────────────────────────────────────────────────
        private async Task<string?> ConvertToPdfAsync(string pptPath, string outDir, CancellationToken ct)
        {
            var args = $"--headless --convert-to pdf --outdir \"{outDir}\" \"{pptPath}\"";
            var ok = await RunLibreOfficeAsync(args, ct);
            if (!ok) return null;

            // LO names output: original_filename.pdf
            var expected = Path.Combine(outDir, Path.GetFileNameWithoutExtension(pptPath) + ".pdf");
            return File.Exists(expected) ? expected : null;
        }

        private async Task<int> ConvertPdfToSlidesAsync(string pdfPath, string outDir, CancellationToken ct)
        {
            var scriptPath = Path.Combine(Directory.GetCurrentDirectory(), "Scripts", "convert_pdf_to_slides.py");
            
            if (!File.Exists(scriptPath))
            {
                _logger.LogError("PyMuPDF Helper Script not found at expected path: {ScriptPath}", scriptPath);
                return 0;
            }

            _logger.LogInformation("Invoking python rasterizer script. Path: {Script}", scriptPath);
            var args = $"\"{scriptPath}\" \"{pdfPath}\" \"{outDir}\"";
            var success = await RunPythonScriptAsync(args, ct);

            if (!success)
            {
                _logger.LogError("PyMuPDF conversion subprocess execution failure.");
                return 0;
            }

            // Count physical PNG results
            var slides = Directory.GetFiles(outDir, "slide_*.png").Length;
            return slides;
        }

        private async Task<bool> RunPythonScriptAsync(string arguments, CancellationToken ct)
        {
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "python",
                    Arguments = arguments,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using var proc = Process.Start(psi);
                if (proc == null) return false;

                using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                cts.CancelAfter(TimeSpan.FromSeconds(90));

                await proc.WaitForExitAsync(cts.Token);
                var stdout = await proc.StandardOutput.ReadToEndAsync();
                var stderr = await proc.StandardError.ReadToEndAsync();

                if (!string.IsNullOrWhiteSpace(stderr))
                    _logger.LogWarning("Python script error logs: {Log}", stderr);
                
                if (!string.IsNullOrWhiteSpace(stdout))
                    _logger.LogDebug("Python script output: {Log}", stdout);

                return proc.ExitCode == 0;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to execute Python runner process for arguments: {Args}", arguments);
                return false;
            }
        }

        private async Task<bool> RunLibreOfficeAsync(string arguments, CancellationToken ct)
        {
            try
            {
                var psi = new ProcessStartInfo
                {
                    FileName = _libreOfficePath,
                    Arguments = arguments,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using var proc = Process.Start(psi);
                if (proc == null) return false;

                using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                cts.CancelAfter(TimeSpan.FromSeconds(120));

                await proc.WaitForExitAsync(cts.Token);
                var stderr = await proc.StandardError.ReadToEndAsync();

                if (!string.IsNullOrWhiteSpace(stderr))
                    _logger.LogDebug("LibreOffice stderr: {Stderr}", stderr);

                return proc.ExitCode == 0 || true; // LO may return non-zero but still succeed
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "LibreOffice process error for args: {Args}", arguments);
                return false;
            }
        }
    }

    // ── Small helper to inject IWebHostEnvironment path without circular dependency ──
    public interface IWebHostEnvironmentAccessor { string WebRootPath { get; } }
    public class WebHostEnvironmentAccessor : IWebHostEnvironmentAccessor
    {
        public string WebRootPath { get; }
        public WebHostEnvironmentAccessor(Microsoft.AspNetCore.Hosting.IWebHostEnvironment env)
            => WebRootPath = env.WebRootPath;
    }
}
